#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: false
  source:
    id: ubuntu-server-minimal
    search_drivers: false
  apt:
    geoip: false
    fallback: offline-install
  locale: en_US.UTF-8
  keyboard:
    layout: us
  network:
    version: 2
    ethernets:
      ens18:
        addresses:
          - ${hostname.ip}/24
        routes:
          - to: default
            via: ${subnet.gateway}
        nameservers:
          addresses:
            - ${subnet.dns1}
            - ${subnet.dns2}
  storage:
    layout:
      name: lvm
      sizing-policy: scaled
  identity:
    hostname: ${hostname.fqn}
    realname: ${username.user}
    username: ${username.user}
    password: "${hashedPassword.password}"
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - qemu-guest-agent
    - openssh-server
  updates: security
  late-commands:
    - echo '${username.user} ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/${username.user}
    - curtin in-target --target=/target -- chmod 440 /etc/sudoers.d/${username.user}
    - curtin in-target --target=/target -- systemctl enable qemu-guest-agent
    - curtin in-target --target=/target -- systemctl enable ssh
  shutdown: reboot